config/routes.rb
Substash::Application.routes.draw do
  devise_for :users

  match "subtitles/:id.zip" => 'subtitles#download', :as => 'subtitle_download'
  resources :subtitles

  get "landing/index"

  root :to => 'landing#index'
end

app/models/episode.rb
class Episode < ActiveRecord::Base
  belongs_to :show
  has_many :subtitles
end

app/models/show.rb
class Show < ActiveRecord::Base
  has_many :episodes
end

app/models/subtitle.rb
require 'carrierwave/orm/activerecord'

class Subtitle < ActiveRecord::Base
  belongs_to :episode

  scope :top_downloads, order('downloads DESC').limit(10)
  scope :newest, order('updated_at DESC').limit(10)

  mount_uploader :file, FileUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
    if user_signed_in?
      @subtitles = Subtitle.newest
    else
      @subtitles = Subtitle.top_downloads
    end
  end
end

app/controllers/subtitles_controller.rb
class SubtitlesController < ApplicationController
  def show
    @subtitle = Subtitle.find(params[:id])
  end

  def download
    subtitle = Subtitle.find(params[:id])
    if subtitle.file.current_path
      subtitle.update_attributes :downloads => (subtitle.downloads + 1)
      send_file subtitle.file.current_path,
        :filename => "#{subtitle.episode.show.title}-S#{subtitle.episode.season}E#{subtitle.episode.number}.zip", 
        :type => "application/zip", :x_sendfile => true
    end
  end

  def new
    @subtitle = Subtitle.new
  end

  def create
    @subtitle = Subtitle.new(params[:subtitle])
    if @subtitle.save
      redirect_to @subtitle
    else
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/subtitles_helper.rb
module SubtitlesHelper
end

app/views/landing/_subtitle.html.erb
<li class="<%= featured ? 'twelvecol featured' : 'fourcol' %> <%= 'last' if last %> subtitle">
<article>
<footer>
<%= link_to "#{subtitle.episode.show.title} Season #{subtitle.episode.season} Episode #{subtitle.episode.number}", subtitle %>
</footer>
</article>
</li>

app/views/landing/index.html.erb
<% if @subtitles.empty? %>
  No subtitles yet. Would you like to upload one now?
<% else %>
  <div class="row">
    <% if user_signed_in? %>
      <h1>Newest</h1>
    <% else %>
      <h1>Top Downloads</h1>
    <% end %>
  </div>

  <ul class="featured subtitles row">
    <%= render :partial => 'subtitle', :object => @subtitles.first, :locals => {:featured => true, :last => false} %>
    <% (0..2).each do |r| %>
      <div class="subtitles row">
        <% (1..3).each do |i| %>
          <%= render(:partial => 'subtitle', :object => @subtitles[i+(3*r)], :locals => {:featured => false, :last => i == 3}) if @subtitles[i+3*r] %>
        <% end %>
      </div>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Substash</title>
    <%= stylesheet_link_tag    "1140", "styles", "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0" />
  </head>
  <body>
    <header>
    <h1 class='logo'>
      <a href="#">
        Substash.tv
      </a>
    </h1>
    </header>
    <div class="container">
      <div class='alert'><%= alert %></div>
      <div class='notice'><%= notice %></div>
      <%= yield %>
    </div>
    <footer>
    <div class="row">
      <div class="fourcol">
      </div>
      <div class="fourcol">
      </div>
      <div class="fourcol last">
        <% if user_signed_in? %>
          <%= link_to 'Sign out', destroy_user_session_path, :method => :delete %>
          <%= link_to 'Upload subtitle', new_subtitle_path %>
        <% else %>
          <%= form_for("user", :url => user_session_path, :html => {:class => 'login'}) do |f| %>
            <p>
            <%= f.label :email, 'E-mail' %>
            <%= f.email_field :email, :placeholder => 'E-mail' %>
            </p>
            <p>
            <%= f.label :password %>
            <%= f.password_field :password, :placeholder => 'Password' %>
            </p>
            <p>
            <%= f.submit 'Sign in' %>
            </p>
          <% end %>
        <% end %>
      </div>
    </div>
    </footer>
  </body>
</html>

app/views/subtitles/new.html.erb
<article class="row subtitle-details">
<h1>New Subtitle</h1>
<footer class="fourcol">
<img src="#" alt="#" />
</footer>
<div class='content eightcol last'>
  <%= form_for(@subtitle) do |f| %>
    <p>
    <%= fields_for(:show) do |s| %>
      <%= s.label :title, 'Show' %>
      <%= s.text_field :title %>
      <%= s.hidden_field :id %>
    <% end %>
    </p>
    <p>
    <%= fields_for(:episode) do |e| %>
      <%= e.label :label, 'Episode' %>
      <%= e.text_field :label %>
    <% end %>
    </p>
    <p>
    <%= f.hidden_field :episode_id %>
    <%= f.label :file %>
    <%= f.file_field :file %>
    <%= f.submit 'Save' %>
    </p>
  <% end %>
</div>
</article>

app/views/subtitles/show.html.erb
<article class="row subtitle-details">
  <h1><%= @subtitle.episode.show.title %></h1>
  <footer class="fourcol">
    <img src="#" alt="#" />
  </footer>
  <div class='content eightcol last'>
    <h2><%= @subtitle.episode.title %></h2>
    <%= link_to "Download", subtitle_download_path(@subtitle) %>
  </div>
</article>